# Generated by Django 2.2.4 on 2019-08-14 10:01

from django.db import migrations, models
import open_event.evento.utils.views


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Palestrante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='nome')),
                ('slug', models.SlugField(verbose_name='slug')),
                ('photo', models.URLField(verbose_name='foto')),
                ('website', models.URLField(blank=True, verbose_name='website')),
                ('description', models.TextField(blank=True, verbose_name='descrição')),
            ],
            options={
                'verbose_name': 'palestrante',
                'verbose_name_plural': 'palestrantes',
            },
        ),
        migrations.CreateModel(
            name='Patrocinio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nome')),
                ('photo', models.URLField(verbose_name='foto')),
                ('nivel', models.IntegerField(choices=[(1, 'Silver'), (2, 'Gold')], verbose_name='Nivel')),
            ],
            options={
                'verbose_name': 'Patrocinio',
                'verbose_name_plural': 'Patrocinios',
            },
        ),
        migrations.AlterModelOptions(
            name='inscrito',
            options={'ordering': ('-date',), 'verbose_name': 'inscrição', 'verbose_name_plural': 'inscrições'},
        ),
        migrations.AlterField(
            model_name='inscrito',
            name='cpf',
            field=models.CharField(max_length=11, validators=[open_event.evento.utils.views.validate_cpf], verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='inscrito',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='criado em'),
        ),
        migrations.AlterField(
            model_name='inscrito',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='e-mail'),
        ),
        migrations.AlterField(
            model_name='inscrito',
            name='name',
            field=models.CharField(max_length=100, verbose_name='nome'),
        ),
        migrations.AlterField(
            model_name='inscrito',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Telefone'),
        ),
    ]
