# Generated by Django 2.2.4 on 2019-08-14 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0003_remove_palestrante_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='palestrante',
            name='social_midia',
            field=models.CharField(blank=True, max_length=20, verbose_name='social midia'),
        ),
    ]
