# Generated by Django 2.2.4 on 2019-08-18 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0005_agenda'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agenda',
            name='arquivo',
        ),
    ]
